### ISSUE TITLE
"Stack smashing error" when trying to run the demo

### ISSUE THREAD

**Issue by tuanna-hsp** [asdfjkl/ctegaki-lib#2]
Error with G++ 5.3, Ubuntu 14.04

**Comment by asdfjkl** [comment]
Thanks for reporting. I am slightly busy with other projects right now. I'll look into it asap!

**Comment by tuanna-hsp** [comment]
Thank you, looking forward it :+1:

**Comment by asdfjkl** [comment]
I can't reproduce this here on a vanilla Ubuntu 14.04 64bit. Compiles fine and runs fine:

``` shellscript
asdfjkl@ubuntu:~/ctegaki-lib/demo$ ./tegaki 
日 目 田 ٸ 由 且 召 ロ 自 囚 寡
```

1.) Standard g++ is 

``` shellscript
g++ -v
[...]
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1) 
```

Any specific requirement on why you use g++ 5.3? How did you install g++ 5.3? Could you try with the default gcc and look if the bug still occurrs?
2.) If you are on a 64bit system: Did you try to build the pattern data? The supplied pattern data are only for 32bit.
3.) If you are on a 32bit system: Can you try to build the pattern data and use those instead of the supplied ones? Does the bug still occurr then?

**Comment by tuanna-hsp** [comment]
Make gave out following error:
![capture2](https://cloud.githubusercontent.com/assets/14136939/14519324/489a7eda-0248-11e6-8688-240f065a23c8.PNG)

So i manually compile and run
![capture](https://cloud.githubusercontent.com/assets/14136939/14519331/5959a426-0248-11e6-88ba-772156a77efb.PNG)

I have just reinstalled Lubuntu 15.10 32bit, so GCC is newer (5.2.1)
I will try again with with old version soon.

**Comment by asdfjkl** [comment]
well the error message apparently says that the linker can't find the lib.
And looking at your screenshot, you have no

 /ctegaki-lib/demo/lib/libctegaki.a

and when you call make in /ctegaki-lib/demo, the linker is looking for a lib subdirectory.

so, either try to create that lib subdirectory within demo and copy the lib to it, or change the include-dir in the makefile according to your directory structure....
So I doubt that you have an issue with GCC or a bug within the lib, it's just that you failed to link the lib.

**Comment by asdfjkl** [comment]
it seems your issue has been solved. Otherwise, please open a new one...
